#!/bin/bash
commit_nbr=$1
num_of_lines=$(git log --oneline | wc -l)
line_of_nth_commit=`expr $num_of_lines - $commit_nbr + 1`

git_number=$(git log --oneline| sed -e $line_of_nth_commit'q;d'| awk '{ print $1, "\t"}')
git checkout $git_number
